#!/usr/bin/env -S python3 -u

# Jackson Green and Tim Doyle
# Networks and Distributed Systems
# TF 9:50 AM Section and TF 3:25 PM Section, respectively
# Prof. Alden Jackson
# Project 3: BGP Router
# Coded in Python

import argparse, socket, time, json, select, struct, sys, math

# maskLength: str -> int
# Expects a netmask expressed as a string in the b10.b10.b10.b10 format. 
# Returns the number of bits to be masked.
def maskLength(str):
    return sum(map(lambda x: bin(x).count("1"), map(int, str.split("."))))

# binarify: str -> int
# Expects an IP Address expressed as a string in the b10.b10.b10.b10 format. 
# Returns the binary expression of the IP Address as an Integer. 
# Since the result of this function is expressed as a Base 10 Integer for simplicity's sake, bit shifts are performed throughout this 
#   program by multiplying and dividing by powers of 10. 
def binarify(ip):
    return int("".join(map(lambda x: x.split("b")[1].rjust(8, "0"), map(str, map(bin, map(int, ip.split(".")))))))

# ipInRange: str, str, str -> bool
# Expects two IP Addresses followed by a netmask, both expressed as a string in the b10.b10.b10.b10 format. 
# Returns True if the first given IP Address is within the range expressed by the second IP Address and the netmask. 
def ipInRange(ip, network, netmask):
    mask = 32 - maskLength(netmask)
    rangeip = binarify(network) // (10 ** mask)
    targetip = binarify(ip) // (10 ** mask)
    return rangeip == targetip

# isNumAdj: str, str, str -> bool
# Expects two IP Addresses followed by a netmask, both expressed as a string in the b10.b10.b10.b10 format. 
# Returns True if, when using the given netmask to truncate bits, the two IP Addresses differ in the ones place, and only the ones place. 
def isNumAdj(network1, network2, netmask):
    mask = 32 - maskLength(netmask)
    ip1 = binarify(network1) // (10 ** mask)
    ip2 = binarify(network2) // (10 ** mask)
    return (ip1 != ip2) and (ip1 // 10 == ip2 // 10)

# decrementMask: str -> str
# Expects a netmask expressed as a string in the b10.b10.b10.b10 format. 
# Returns a netmask that is exactly one bit smaller, also expressed in the b10.b10.b10.b10 format. 
def decrementMask(netmask):
    mask = maskLength(netmask) - 1
    final = ""
    while mask > 8:
        mask -= 8
        final += "255."
    mask = 256 - (2 ** (8 - mask))
    final += "%d" % (mask)
    while len(final.split(".")) < 4:
        final += ".0"
    return final

# lesserIP: str, str -> str
# Expects two IP Addresses, both expressed as a string in the b10.b10.b10.b10 format. 
# Returns the lesser of the two IP Addresses. 
def lesserIP(ip1, ip2):
    if (binarify(ip1) > binarify(ip2)):
        return ip2
    return ip1

# pathSorter: dict -> int
# Expects a dictionary containing fields that identify it as an expression of a valid path for messages. 
# Returns an integer determining the priority of this route, for the purpose of comparing against other routes.
# The larger the number returned, the "better" the route is, according to the specifications within test case groups 2 and 5. 
def pathSorter(p):
    a = 0
    a *= 100
    a += maskLength(p["netmask"])
    a *= 1000
    a += ((p["localpref"] if p["localpref"] < 1000 else 999) if p["localpref"] > 0 else 0)
    a += (1 if p["selfOrigin"] else 0)
    a *= 100
    a += 99 - (len(p["ASPath"]) if len(p["ASPath"]) < 100 else 99)
    a *= 10
    a += (3 if p["origin"] == "IGP" else (2 if p["origin"] == "EGP" else 1))
    ipSplit = list(map(int, p["network"].split(".")))
    a *= 1000
    a += 256 - ipSplit[0]
    a *= 1000
    a += 256 - ipSplit[1]
    a *= 1000
    a += 256 - ipSplit[2]
    a *= 1000
    a += 256 - ipSplit[3]
    return a

# Router
# Primary Class. Stores data and functionality of a Simple BGP Router.
class Router:
    debug = True
    relations = {}
    sockets = {}
    ports = {}
    routing = []
    neighbors = []
    inbox = []

    # __init__: int, list -> Router
    # Expects an ASN Number, and a list of other Routers in the network.
    # Initializes Router according to given parameters.
    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        for self.relationship in connections:
            port, neighbor, relation = self.relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            self.neighbors.append(neighbor)
            self.send(neighbor, json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {} }))

    # our_addr: str -> str
    # Expects a valid destination.
    # Returns this Router's address, according to the destination.
    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    # send: str, str
    # Expects the IP Address of a peer, expressed in b10.b10.b10.b10 format, and a message to be sent.
    # Sends a message to another router in the network. 
    def send(self, network, message):
        print("Sending message '%s' to %s" % (message, network))
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    # reaggregate
    # Reaggregates Routing Table. 
    def reaggregate(self):
        agg = False
        for i in range(1, len(self.routing)):
            for j in range(0, i):
                if self.routing[i]["peer"] == self.routing[j]["peer"] and self.routing[i]["localpref"] == self.routing[j]["localpref"] and self.routing[i]["selfOrigin"] == self.routing[j]["selfOrigin"] and self.routing[i]["ASPath"] == self.routing[j]["ASPath"] and self.routing[i]["origin"] == self.routing[j]["origin"] and isNumAdj(self.routing[i]["network"], self.routing[j]["network"], self.routing[i]["netmask"]):
                    r1 = self.routing.pop(i)
                    r2 = self.routing.pop(j)
                    print(r1)
                    print(r2)
                    self.routing.append(self.routing.append({"peer": r1["peer"], "network": lesserIP(r1["network"], r2["network"]), "netmask": decrementMask(r1["netmask"]) if r1["netmask"] == r2["netmask"] else lesserIP(r1["network"], r2["network"]), "localpref": r1["localpref"], "selfOrigin": r1["selfOrigin"], "ASPath": r1["ASPath"], "origin": r1["origin"], "subroutes": [r1, r2]}))
                    self.routing = [x for x in self.routing if x != None]
                    print(self.routing[-1])
                    agg = True
                    break
            if agg:
                break
        if agg:
            self.reaggregate()

    # newRemove: list, str, OPTIONAL dict -> list, list
    # Expects a list of routes to try and remove, the peer that is requesting the routes be removed, and (optionally), a route whose  
    #   subroutes will be checked instead of the main routing table. 
    # Removes the given routes from the routing table. Recursively checks aggregated subroutes and disaggregates (in theory). 
    def newRemove(self, rmroutes, srcif, sroute=None):
        removeUs = []
        newRoutes = []
        for netCompare in rmroutes:
            for route in self.routing if (sroute == None) else sroute["subroutes"]:
                if route["peer"] == srcif and route["network"] == netCompare["network"] and route["netmask"] == netCompare["netmask"]:
                    removeUs.append(route)
                    break
                elif len(route["subroutes"]) > 0:
                    foo, bar = self.newRemove([r for r in rmroutes if r not in removeUs], srcif, route)
                    removeUs.extend(foo)
                    newRoutes.extend(bar)
        if (sroute == None):
            self.routing = [x for x in self.routing if x not in removeUs]
            for nr in newRoutes:
                self.routing.append(nr)
        return removeUs, newRoutes

    # run
    # Runs the Router. 
    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break
                msg = json.loads(k.decode('utf-8'))
                self.inbox.append(msg)
                print("\n------- NEW MESSAGE RECVD -------")
                print("Received message '%s' from %s" % (msg, srcif))
                if msg["type"] == "update":
                    self.routing.append({"peer": msg["src"], "network": msg["msg"]["network"], "netmask": msg["msg"]["netmask"], "localpref": msg["msg"]["localpref"], "selfOrigin": msg["msg"]["selfOrigin"], "ASPath": msg["msg"]["ASPath"], "origin": msg["msg"]["origin"], "subroutes": []})
                    self.reaggregate()
                    newASPath = [self.asn]
                    newASPath.extend(msg["msg"]["ASPath"])
                    for neighbor in self.neighbors:
                        if (self.relations[srcif] == "cust" or self.relations[neighbor] == "cust") and neighbor != srcif:
                            self.send(neighbor, json.dumps({ "type": "update", "src": self.our_addr(neighbor), "dst": neighbor, "msg": { "network": msg["msg"]["network"], "netmask": msg["msg"]["netmask"], "ASPath": newASPath } }))
                elif msg["type"] == "withdraw":
                    self.newRemove(msg["msg"], srcif)
                    for neighbor in self.neighbors:
                        if (self.relations[srcif] == "cust" or self.relations[neighbor] == "cust") and neighbor != srcif:
                            self.send(neighbor, json.dumps({ "type": "withdraw", "src": self.our_addr(neighbor), "dst": neighbor, "msg": msg["msg"] }))
                elif msg["type"] == "data":
                    pathOptions = []
                    for route in self.routing:
                        if ipInRange(msg["dst"], route["network"], route["netmask"]) and (self.relations[route["peer"]] == "cust" or self.relations[srcif] == "cust"):
                            pathOptions.append(route)
                            print("Optioned Route through peer " + route["peer"] + ", found VIABLE")
                        else:
                            print("Optioned Route through peer " + route["peer"] + ", found UNVIABLE")
                    if len(pathOptions) < 1:
                        self.send(srcif, json.dumps({ "type": "no route", "src": self.our_addr(neighbor), "dst": srcif, "msg": {} }))
                    else:
                        if len(pathOptions) > 1:
                            pathOptions.sort(reverse=True, key=pathSorter)
                        chosenPath = pathOptions[0]
                        self.send(chosenPath["peer"], json.dumps({ "type": "data", "src": self.our_addr(neighbor), "dst": msg["dst"], "msg": msg["msg"] }))
                elif msg["type"] == "dump":
                    self.send(msg["src"], json.dumps({ "type": "table", "src": self.our_addr(neighbor), "dst": msg["src"], "msg": list(map(lambda x: {key: val for key, val in x.items() if key != 'subroutes'}, self.routing)) }))
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
